name: yolda_app
description: "\"Yo'lda\" mobil ilovasi"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Cupertino icons
  cupertino_icons: ^1.0.2

  # Development and debugging
  logger: ^2.0.2+1

  # Firebase
  firebase_core: ^2.24.2
  firebase_remote_config: ^4.3.8
  firebase_analytics: ^10.7.4

  # Local storage
  shared_preferences: ^2.2.2

  # Localization
  easy_localization: ^3.0.3

  # Connection Checkers
  observe_internet_connectivity: ^1.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  # Rules
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700