name: yolda_app
description: "\"Yo'lda\" mobil ilovasi"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Cupertino icons
  cupertino_icons: ^1.0.2

  # Development and debugging
  logger: ^2.0.2+1

  # Firebase
  firebase_core: ^2.24.2
  firebase_remote_config: ^4.3.8
  firebase_analytics: ^10.7.4

  # Local storage
  shared_preferences: ^2.2.2

  # Localization
  easy_localization: ^3.0.3

  # Connection Checkers
  observe_internet_connectivity: ^1.0.2
  provider: ^6.1.1
  package_info_plus: ^5.0.1
  google_maps_flutter: ^2.5.0
  flutter_tts: ^3.8.5
  geofence_service: ^5.0.0
  geolocator: ^10.1.0
  pinput: ^3.0.1
  mask_text_input_formatter: ^2.7.0
  flutter_screenutil: ^5.9.0
  permission_handler: ^11.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  # Rules
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/

  fonts:
    - family: RaviPrakash
      fonts:
        - asset: assets\fonts\RaviPrakash-Regular.ttf
          weight: 400
    - family: Righteous
      fonts:
        - asset: assets\fonts\Righteous-Regular.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: assets\fonts\roboto\Roboto-Regular.ttf
          weight: 400